---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source: embed
---

```{r setup, include=FALSE}
library(tidyverse)
library(p8105.datasets)
library(plotly)

library(flexdashboard)
```

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Waikiki_HA",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
```

Column {data-width=550}
-----------------------------------------------------------------------

### Scatterplot

```{r}
weather_df %>%
  mutate(text_label = str_c("Min Temp: ", tmin, "\nMax Temp: ", tmax)) %>% #\n: next line;
  plot_ly(
    x = ~tmin, y = ~tmax, type = "scatter", mode = "markers",
    color = ~name, text = ~text_label, alpha = 0.5) %>% 
  layout(xaxis = list(title = "Minimum daily temperature (C)"),
         yaxis = list(title = "Maxiumum daily temperature (C)"),
         title = "Scatterplot of daily temperature (C)")

```

Column {data-width=450}
-----------------------------------------------------------------------

### Chart B

```{r}

```

### Chart C

```{r}


```


